### ISSUE TITLE
how to move camera when user scroll up or down

### ISSUE THREAD

**Issue by chengsokneng** [Aralekk/simple360player_iOS#9]
i want to move camera when user scroll up or down can you help me sir

**Comment by Aralekk** [comment]
I've wrote the code today, I'll push it tomorrow I think

**Comment by chengsokneng** [comment]
thank sir

**Comment by Aralekk** [comment]
Done

**Comment by chengsokneng** [comment]
sir on Landscape it fine when user scroll up and down but on Portrait still wrong can you fix it for me please

**Comment by Aralekk** [comment]
the issue comes from the angle modification made on phone rotation in this function "getCamerasNodeAngle"
I pushed the commit a bit quickly sorry, you can account for the difference in your code

I'll come around and push a fix some times soon :)

**Comment by chengsokneng** [comment]
okay thank sir :)

**Comment by chengsokneng** [comment]
i still can't account on it :( can you help me for this issue sir :(
